language: go
matrix:
  include:
  - os: linux
    dist: xenial
    go: 1.10.x
  - os: linux
    dist: xenial
    go: 1.11.x
  - os: linux
    dist: xenial
    go: master
  - os: osx
    go: 1.10.x
  - os: osx
    go: 1.11.x
  - os: osx
    go: master
  allow_failures:
  - go: master
  fast_finish: true
go_import_path: github.com/liamg/aminal
before_install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install -y xorg-dev libgl1-mesa-dev
  gcc-multilib gcc-mingw-w64-x86-64 xvfb vttest && go get github.com/mitchellh/gox;
  fi
script:
- go get
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then xvfb-run --server-args="-screen 0 1024x768x24"
  make test; else make test; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then make build-darwin-native-travis; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then make build-linux-travis; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then make windows-cross-compile-travis; fi
before_deploy:
  - export CHANGELOG=$(git log $(git describe --abbrev=0 --tags "${TRAVIS_TAG}^")..$TRAVIS_TAG --pretty=format:'<li> <a href="http://github.com/liamg/aminal/commit/%H">view commit &bull;</a> %s</li> ' --reverse | while read line; do echo -n "$line "; done)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KfYypMUBWC0nIJnmfxO2sXboUmUoMAeBSPgn1s7SYRl7+7GiR7mcl4yz80BC3o/8ef1DfH9bMnYtzUQzPn2YZJqatzSqyn/vTQszOdp5fLEUVHkHOWgFJ56QRTqq3FMwTrfIrzSld675ZXPeH7L1jVM0XjxckWYkufKBk5/848Pwy7Wx8FzaME0wuoqr/9SG7GfjpZwvLfUwOXN2TX0zyajLEhYZ6Xgtt/PSXlLLh+r6NSoU+jM/3TYe2knMrLdLHfPoMYs4g11VYIMUyxyZrpUvbEbEZfHYOaKLIznROJOkxCC26V/svIXzeFiZOP48pP/pqzITInBydgpxsAHWWfhavOdY42r5WDNBBxjmJbgRH6lw9Htbh8EeFA6Ptlg6s1q/r3lyPoJmMT1gsumkrMRHvXwEe16PyvmZr1mX/IRqgtnEyYZGxVrYSTDd1QoFC9V9+BdIUfsnO5iEupoYmJ/v3MDQupWKD0ZkufTssKuMpc4pL0b/OnsgDEniEM7ssBL2T0drJPYoA1p0BbvSpA0fktue0SqVRjPvvLlRJF7sOwvgahuMW158Tou1OBb1TMsFBa8jyQpaBv3D8JHEWNgXi/WRWPQn5HQ59gqP9R1SUrkFwSYq4pxH0VTh8ocdjujup3YjzDvYqQsC0uWrZtxQ0FJUJPfLZcIDaaKcgis=
  name: "Aminal $TRAVIS_TAG"
  body: ${CHANGELOG}
  file:
    - bin/darwin/aminal-darwin-amd64
    - bin/linux/aminal-linux-amd64
    - bin/windows/aminal-windows-amd64.exe
  on:
    repo: MaxRis/aminal
    tags: true
    condition: "$TRAVIS_GO_VERSION =~ ^1\\.11"
